// Code generated by MockGen. DO NOT EDIT.
// Source: webpush.go
//
// Generated by this command:
//
//	mockgen -package=webpush -destination=webpush_mock.go -source=webpush.go
//

// Package webpush is a generated GoMock package.
package webpush

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWebPush is a mock of WebPush interface.
type MockWebPush struct {
	ctrl     *gomock.Controller
	recorder *MockWebPushMockRecorder
	isgomock struct{}
}

// MockWebPushMockRecorder is the mock recorder for MockWebPush.
type MockWebPushMockRecorder struct {
	mock *MockWebPush
}

// NewMockWebPush creates a new mock instance.
func NewMockWebPush(ctrl *gomock.Controller) *MockWebPush {
	mock := &MockWebPush{ctrl: ctrl}
	mock.recorder = &MockWebPushMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebPush) EXPECT() *MockWebPushMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockWebPush) Send(ctx context.Context, payload []byte, subscription Subscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, payload, subscription)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockWebPushMockRecorder) Send(ctx, payload, subscription any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockWebPush)(nil).Send), ctx, payload, subscription)
}

// SendMany mocks base method.
func (m *MockWebPush) SendMany(ctx context.Context, payload []byte, subscriptions []Subscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMany", ctx, payload, subscriptions)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMany indicates an expected call of SendMany.
func (mr *MockWebPushMockRecorder) SendMany(ctx, payload, subscriptions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMany", reflect.TypeOf((*MockWebPush)(nil).SendMany), ctx, payload, subscriptions)
}
