CREATE TABLE accounts (
    id          VARCHAR(1024) PRIMARY KEY,
    email       VARCHAR(1024) NOT NULL,
    password    VARCHAR(1024) NOT NULL,
    created_at  TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at  TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE rooms (
    id          VARCHAR(1024) PRIMARY KEY,
    name        VARCHAR(1024) NOT NULL,
    owner_id    VARCHAR(1024) NOT NULL,
    owner_type  VARCHAR(1024) NOT NULL,
    created_at  TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at  TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_rooms_owner
        FOREIGN KEY (owner_id)
        REFERENCES accounts(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_rooms_owner_id ON rooms(owner_id);

CREATE TABLE room_members (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id     VARCHAR(1024) NOT NULL,
    account_id  VARCHAR(1024) NOT NULL,
    role        VARCHAR(50) DEFAULT 'member' NOT NULL,
    created_at  TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at  TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_room_members_room
        FOREIGN KEY (room_id)
        REFERENCES rooms(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_room_members_account
        FOREIGN KEY (account_id)
        REFERENCES accounts(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_room_members_room_id ON room_members(room_id);

CREATE INDEX idx_room_members_account_id ON room_members(account_id);

CREATE UNIQUE INDEX uq_room_members_room_account
ON room_members(room_id, account_id);
