CREATE TABLE ledger_snapshots (
    id             VARCHAR(1024) PRIMARY KEY,
    aggregate_id   VARCHAR(1024) NOT NULL,
    aggregate_type VARCHAR(255)  NOT NULL,
    version        BIGINT     NOT NULL,
    snapshot_data  TEXT           NOT NULL,
    created_at     TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX idx_ledger_snapshots_agg_ver
    ON ledger_snapshots(aggregate_id, aggregate_type, version);

CREATE TABLE ledger_outbox_events (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_id   VARCHAR(1024) NOT NULL,
    aggregate_type VARCHAR(255)  NOT NULL,
    version        BIGINT     NOT NULL,
    event_name     VARCHAR(255)  NOT NULL,
    event_data     TEXT           NOT NULL,
    metadata       TEXT           NOT NULL,
    created_at     TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX idx_ledger_outbox_aggregate_id
    ON ledger_outbox_events(aggregate_id);

CREATE INDEX idx_ledger_outbox_aggregate_type
    ON ledger_outbox_events(aggregate_type);

CREATE INDEX idx_ledger_outbox_event_name
    ON ledger_outbox_events(event_name);
