-- =========================
-- TABLE: payment_balances
-- =========================
CREATE TABLE payment_balances (
    id          VARCHAR2(1024) PRIMARY KEY,
    account_id  VARCHAR2(1024) NOT NULL,
    amount      NUMBER(19)     NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_payment_balances_account_id ON payment_balances(account_id);

-- =========================
-- TABLE: payment_balance_snapshots
-- =========================
CREATE TABLE payment_balance_snapshots (
    id            VARCHAR2(1024) PRIMARY KEY,
    aggregate_id  VARCHAR2(1024) NOT NULL,
    version       NUMBER(10)     NOT NULL,
    state         CLOB           NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX idx_snap_ver
ON payment_balance_snapshots(aggregate_id, version);

-- =========================
-- TABLE: payment_events
-- =========================
CREATE TABLE payment_events (
    id             VARCHAR2(1024) PRIMARY KEY,
    aggregate_id   VARCHAR2(1024) NOT NULL,
    aggregate_type VARCHAR2(255)  NOT NULL,
    version        NUMBER(10)     NOT NULL,
    event_name     VARCHAR2(255)  NOT NULL,
    event_data     CLOB           NOT NULL,
    metadata       CLOB           NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX idx_agg_ver
ON payment_events(aggregate_id, version);
CREATE INDEX idx_payment_events_event_name ON payment_events(event_name);

-- =========================
-- TABLE: payment_event_offsets
-- =========================
CREATE TABLE payment_event_offsets (
    consumer_name VARCHAR2(1024) PRIMARY KEY,
    last_event_id NUMBER(19)     NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

-- =========================
-- TABLE: payment_outbox_events
-- =========================
CREATE TABLE payment_outbox_events (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_id    VARCHAR2(1024) NOT NULL,
    aggregate_type  VARCHAR2(255)  NOT NULL,
    version         NUMBER(10)     NOT NULL,
    event_name      VARCHAR2(255)  NOT NULL,
    event_data      CLOB           NOT NULL,
    metadata        CLOB,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_pay_outbox_aggregate_id ON payment_outbox_events(aggregate_id);
CREATE INDEX idx_pay_outbox_aggregate_type ON payment_outbox_events(aggregate_type);
CREATE INDEX idx_pay_outbox_event_name ON payment_outbox_events(event_name);

-- =========================
-- TABLE: payment_transactions
-- =========================
CREATE TABLE payment_transactions (
    id          VARCHAR2(1024) PRIMARY KEY,
    account_id  VARCHAR2(1024) NOT NULL,
    event_id    VARCHAR2(1024) NOT NULL,
    amount      NUMBER(19)     NOT NULL,
    type        VARCHAR2(255)  NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_payment_transactions_account_id ON payment_transactions(account_id);
CREATE INDEX idx_payment_transactions_event_id ON payment_transactions(event_id);
