CREATE UNIQUE INDEX APPUSER.UQ_ACCOUNTS_EMAIL_NORM
  ON APPUSER.ACCOUNTS (EMAIL_NORM);

CREATE UNIQUE INDEX APPUSER.UQ_ACCOUNTS_USERNAME_NORM
  ON APPUSER.ACCOUNTS (
    CASE
      WHEN USERNAME IS NOT NULL AND TRIM(USERNAME) IS NOT NULL
        THEN LOWER(TRIM(USERNAME))
      ELSE NULL
    END
  );

CREATE INDEX APPUSER.IDX_ACCOUNTS_DISPLAY_NAME_NORM
  ON APPUSER.ACCOUNTS (DISPLAY_NAME_NORM);

CREATE INDEX APPUSER.IDX_ACCOUNTS_STATUS
  ON APPUSER.ACCOUNTS (STATUS);

CREATE OR REPLACE TRIGGER APPUSER.TRG_ACCOUNTS_SET_UPDATED_AT
BEFORE UPDATE ON APPUSER.ACCOUNTS
FOR EACH ROW
BEGIN
  :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/