CREATE UNIQUE INDEX IF NOT EXISTS UQ_ACCOUNTS_EMAIL_NORM
  ON ACCOUNTS (EMAIL_NORM);

CREATE UNIQUE INDEX IF NOT EXISTS UQ_ACCOUNTS_USERNAME_NORM
  ON ACCOUNTS (USERNAME_NORM)
  WHERE USERNAME_NORM IS NOT NULL AND USERNAME_NORM <> '';

CREATE INDEX IF NOT EXISTS IDX_ACCOUNTS_DISPLAY_NAME_NORM
  ON ACCOUNTS (DISPLAY_NAME_NORM);

CREATE INDEX IF NOT EXISTS IDX_ACCOUNTS_STATUS
  ON ACCOUNTS (STATUS);

DROP TRIGGER IF EXISTS trg_accounts_set_updated_at ON accounts;

CREATE OR REPLACE FUNCTION trg_accounts_set_updated_at_fn() RETURNS trigger AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER trg_accounts_set_updated_at BEFORE UPDATE ON accounts FOR EACH ROW EXECUTE FUNCTION trg_accounts_set_updated_at_fn();
