ALTER TABLE APPUSER.ACCOUNTS ADD (
  EMAIL_NORM VARCHAR2(1024)
    GENERATED ALWAYS AS (LOWER(TRIM(EMAIL))) VIRTUAL,
  USERNAME_NORM VARCHAR2(100)
    GENERATED ALWAYS AS (LOWER(TRIM(USERNAME))) VIRTUAL,
  DISPLAY_NAME_NORM VARCHAR2(255)
    GENERATED ALWAYS AS (LOWER(TRIM(DISPLAY_NAME))) VIRTUAL
);

ALTER TABLE APPUSER.ACCOUNTS
  ADD CONSTRAINT CK_ACCOUNTS_STATUS
  CHECK (STATUS IN ('active', 'banned', 'deleted', 'pending'));