CREATE TABLE payment_balances (
    id          VARCHAR(1024) PRIMARY KEY,
    account_id  VARCHAR(1024) NOT NULL,
    amount      BIGINT     NOT NULL,
    created_at  TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX idx_payment_balances_account_id ON payment_balances(account_id);

CREATE TABLE payment_balance_snapshots (
    id            VARCHAR(1024) PRIMARY KEY,
    aggregate_id  VARCHAR(1024) NOT NULL,
    version       BIGINT     NOT NULL,
    state         TEXT           NOT NULL,
    created_at    TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX idx_snap_ver
ON payment_balance_snapshots(aggregate_id, version);

CREATE TABLE payment_events (
    id             VARCHAR(1024) PRIMARY KEY,
    aggregate_id   VARCHAR(1024) NOT NULL,
    aggregate_type VARCHAR(255)  NOT NULL,
    version        BIGINT     NOT NULL,
    event_name     VARCHAR(255)  NOT NULL,
    event_data     TEXT           NOT NULL,
    metadata       TEXT           NOT NULL,
    created_at     TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX idx_agg_ver
ON payment_events(aggregate_id, version);

CREATE INDEX idx_payment_events_event_name ON payment_events(event_name);

CREATE TABLE payment_event_offsets (
    consumer_name VARCHAR(1024) PRIMARY KEY,
    last_event_id BIGINT     NOT NULL,
    updated_at    TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE payment_outbox_events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_id    VARCHAR(1024) NOT NULL,
    aggregate_type  VARCHAR(255)  NOT NULL,
    version         BIGINT     NOT NULL,
    event_name      VARCHAR(255)  NOT NULL,
    event_data      TEXT           NOT NULL,
    metadata        TEXT,
    created_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX idx_pay_outbox_aggregate_id ON payment_outbox_events(aggregate_id);

CREATE INDEX idx_pay_outbox_aggregate_type ON payment_outbox_events(aggregate_type);

CREATE INDEX idx_pay_outbox_event_name ON payment_outbox_events(event_name);

CREATE TABLE payment_transactions (
    id          VARCHAR(1024) PRIMARY KEY,
    account_id  VARCHAR(1024) NOT NULL,
    event_id    VARCHAR(1024) NOT NULL,
    amount      BIGINT     NOT NULL,
    type        VARCHAR(255)  NOT NULL,
    created_at  TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX idx_payment_transactions_account_id ON payment_transactions(account_id);

CREATE INDEX idx_payment_transactions_event_id ON payment_transactions(event_id);
