ALTER TABLE ROOM_MEMBERS ADD (ID_NEW VARCHAR2(36));

UPDATE ROOM_MEMBERS
SET ID_NEW = TO_CHAR(ID);

ALTER TABLE ROOM_MEMBERS DROP PRIMARY KEY;

ALTER TABLE ROOM_MEMBERS DROP COLUMN ID;

ALTER TABLE ROOM_MEMBERS RENAME COLUMN ID_NEW TO ID;

ALTER TABLE ROOM_MEMBERS MODIFY (ID VARCHAR2(36) NOT NULL);

ALTER TABLE ROOM_MEMBERS ADD CONSTRAINT PK_ROOM_MEMBERS PRIMARY KEY (ID);