DROP TRIGGER IF EXISTS TRG_ACCOUNTS_SET_UPDATED_AT ON accounts;

DROP FUNCTION IF EXISTS trg_accounts_set_updated_at_fn();

DROP INDEX IDX_ACCOUNTS_STATUS;

DROP INDEX IDX_ACCOUNTS_DISPLAY_NAME_NORM;

DROP INDEX UQ_ACCOUNTS_USERNAME_NORM;

DROP INDEX UQ_ACCOUNTS_EMAIL_NORM;
