DROP TRIGGER APPUSER.TRG_ACCOUNTS_SET_UPDATED_AT;

DROP INDEX APPUSER.IDX_ACCOUNTS_STATUS;
DROP INDEX APPUSER.IDX_ACCOUNTS_DISPLAY_NAME_NORM;
DROP INDEX APPUSER.UQ_ACCOUNTS_USERNAME_NORM;
DROP INDEX APPUSER.UQ_ACCOUNTS_EMAIL_NORM;