ALTER TABLE ACCOUNTS DROP CONSTRAINT CK_ACCOUNTS_STATUS;

ALTER TABLE ACCOUNTS DROP COLUMN DISPLAY_NAME_NORM;

ALTER TABLE ACCOUNTS DROP COLUMN USERNAME_NORM;

ALTER TABLE ACCOUNTS DROP COLUMN EMAIL_NORM;
