CREATE TABLE APPUSER.ROOM_ACCOUNT_PROJECTIONS (
  ACCOUNT_ID         VARCHAR2(1024) NOT NULL,
  DISPLAY_NAME       VARCHAR2(1024) DEFAULT '' NOT NULL,
  USERNAME           VARCHAR2(1024) DEFAULT '' NOT NULL,
  AVATAR_OBJECT_KEY  VARCHAR2(2048) DEFAULT '' NOT NULL,
  UPDATED_AT         TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  CREATED_AT         TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_ROOM_ACCOUNT_PROJECTIONS PRIMARY KEY (ACCOUNT_ID)
);

CREATE INDEX IDX_RAP_DISPLAY_NAME
ON APPUSER.ROOM_ACCOUNT_PROJECTIONS (DISPLAY_NAME);

CREATE INDEX IDX_RAP_USERNAME
ON APPUSER.ROOM_ACCOUNT_PROJECTIONS (USERNAME);