ALTER TABLE room_members ADD COLUMN ID_OLD NUMERIC;

UPDATE ROOM_MEMBERS
SET ID_OLD = NULLIF(ID, '')::numeric;

ALTER TABLE room_members DROP CONSTRAINT IF EXISTS PK_ROOM_MEMBERS;

ALTER TABLE room_members DROP CONSTRAINT IF EXISTS room_members_pkey;

ALTER TABLE ROOM_MEMBERS DROP COLUMN ID;

ALTER TABLE ROOM_MEMBERS RENAME COLUMN ID_OLD TO ID;

ALTER TABLE room_members ALTER COLUMN id TYPE NUMERIC;

ALTER TABLE room_members ALTER COLUMN id SET NOT NULL;

ALTER TABLE ROOM_MEMBERS ADD CONSTRAINT PK_ROOM_MEMBERS PRIMARY KEY (ID);
