UPDATE ROOM_ACCOUNT_PROJECTIONS
SET USERNAME = 'unknown'
WHERE USERNAME IS NULL;

UPDATE ROOM_ACCOUNT_PROJECTIONS
SET AVATAR_OBJECT_KEY = 'none'
WHERE AVATAR_OBJECT_KEY IS NULL;

ALTER TABLE room_account_projections ALTER COLUMN username TYPE VARCHAR(1024);

ALTER TABLE room_account_projections ALTER COLUMN username SET NOT NULL;

ALTER TABLE room_account_projections ALTER COLUMN avatar_object_key TYPE VARCHAR(2048);

ALTER TABLE room_account_projections ALTER COLUMN avatar_object_key SET NOT NULL;
