ALTER TABLE accounts ADD COLUMN EMAIL_NORM VARCHAR(1024)
    GENERATED ALWAYS AS (LOWER(BTRIM(EMAIL))) STORED;

ALTER TABLE accounts ADD COLUMN USERNAME_NORM VARCHAR(100)
    GENERATED ALWAYS AS (LOWER(BTRIM(USERNAME))) STORED;

ALTER TABLE accounts ADD COLUMN DISPLAY_NAME_NORM VARCHAR(255)
    GENERATED ALWAYS AS (LOWER(BTRIM(DISPLAY_NAME))) STORED;

ALTER TABLE ACCOUNTS
  ADD CONSTRAINT CK_ACCOUNTS_STATUS
  CHECK (STATUS IN ('active', 'banned', 'deleted', 'pending'));
