-- =========================
-- MIGRATE: account_outbox_events -> new schema
-- =========================
ALTER TABLE account_outbox_events RENAME TO account_outbox_events_old;

CREATE TABLE account_outbox_events (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_id    VARCHAR2(1024) NOT NULL,
    aggregate_type  VARCHAR2(255)  NOT NULL,
    version         NUMBER(10)     NOT NULL,
    event_name      VARCHAR2(255)  NOT NULL,
    event_data      CLOB           NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

INSERT INTO account_outbox_events (
    aggregate_id,
    aggregate_type,
    version,
    event_name,
    event_data,
    created_at
)
SELECT
    COALESCE(
        JSON_VALUE(event_data, '$.AggregateID' RETURNING VARCHAR2(1024) NULL ON ERROR),
        JSON_VALUE(event_data, '$.AccountID' RETURNING VARCHAR2(1024) NULL ON ERROR),
        'legacy'
    ) AS aggregate_id,
    COALESCE(
        JSON_VALUE(event_data, '$.AggregateType' RETURNING VARCHAR2(255) NULL ON ERROR),
        'account'
    ) AS aggregate_type,
    NVL(
        JSON_VALUE(event_data, '$.Version' RETURNING NUMBER NULL ON ERROR),
        1
    ) AS version,
    SUBSTR(event_name, 1, 255) AS event_name,
    TO_CLOB(event_data) AS event_data,
    created_at
FROM account_outbox_events_old;

DROP TABLE account_outbox_events_old CASCADE CONSTRAINTS;

CREATE INDEX idx_acc_outbox_aggregate_id ON account_outbox_events(aggregate_id);
CREATE INDEX idx_acc_outbox_aggregate_type ON account_outbox_events(aggregate_type);
CREATE INDEX idx_acc_outbox_event_name ON account_outbox_events(event_name);
