ALTER TABLE ROOM_MEMBERS ADD (ID_OLD NUMBER);

UPDATE ROOM_MEMBERS
SET ID_OLD = TO_NUMBER(ID);

ALTER TABLE ROOM_MEMBERS DROP PRIMARY KEY;

ALTER TABLE ROOM_MEMBERS DROP COLUMN ID;

ALTER TABLE ROOM_MEMBERS RENAME COLUMN ID_OLD TO ID;

ALTER TABLE ROOM_MEMBERS MODIFY (ID NUMBER NOT NULL);

ALTER TABLE ROOM_MEMBERS ADD CONSTRAINT PK_ROOM_MEMBERS PRIMARY KEY (ID);