-- =========================
-- TABLE: room_outbox_events
-- =========================
CREATE TABLE room_outbox_events (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_id    VARCHAR2(1024) NOT NULL,
    aggregate_type  VARCHAR2(255)  NOT NULL,
    version         NUMBER(10)     NOT NULL,
    event_name      VARCHAR2(255)  NOT NULL,
    event_data      CLOB           NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_room_outbox_aggregate_id ON room_outbox_events(aggregate_id);
CREATE INDEX idx_room_outbox_aggregate_type ON room_outbox_events(aggregate_type);
CREATE INDEX idx_room_outbox_event_name ON room_outbox_events(event_name);
