ALTER TABLE APPUSER.ACCOUNTS DROP CONSTRAINT CK_ACCOUNTS_STATUS;

ALTER TABLE APPUSER.ACCOUNTS DROP COLUMN DISPLAY_NAME_NORM;
ALTER TABLE APPUSER.ACCOUNTS DROP COLUMN USERNAME_NORM;
ALTER TABLE APPUSER.ACCOUNTS DROP COLUMN EMAIL_NORM;