CREATE TABLE ROOM_ACCOUNT_PROJECTIONS (
  ACCOUNT_ID         VARCHAR(1024) NOT NULL,
  DISPLAY_NAME       VARCHAR(1024) DEFAULT '' NOT NULL,
  USERNAME           VARCHAR(1024) DEFAULT '' NOT NULL,
  AVATAR_OBJECT_KEY  VARCHAR(2048) DEFAULT '' NOT NULL,
  UPDATED_AT         TIMESTAMPTZ NOT NULL,
  CREATED_AT         TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_ROOM_ACCOUNT_PROJECTIONS PRIMARY KEY (ACCOUNT_ID)
);

CREATE INDEX IDX_RAP_DISPLAY_NAME
ON ROOM_ACCOUNT_PROJECTIONS (DISPLAY_NAME);

CREATE INDEX IDX_RAP_USERNAME
ON ROOM_ACCOUNT_PROJECTIONS (USERNAME);
