UPDATE APPUSER.ROOM_ACCOUNT_PROJECTIONS
SET USERNAME = 'unknown'
WHERE USERNAME IS NULL;

UPDATE APPUSER.ROOM_ACCOUNT_PROJECTIONS
SET AVATAR_OBJECT_KEY = 'none'
WHERE AVATAR_OBJECT_KEY IS NULL;

ALTER TABLE APPUSER.ROOM_ACCOUNT_PROJECTIONS MODIFY USERNAME VARCHAR2(1024) NOT NULL;
ALTER TABLE APPUSER.ROOM_ACCOUNT_PROJECTIONS MODIFY AVATAR_OBJECT_KEY VARCHAR2(2048) NOT NULL;