ALTER TABLE account_outbox_events RENAME TO account_outbox_events_old;

CREATE TABLE account_outbox_events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_id    VARCHAR(1024) NOT NULL,
    aggregate_type  VARCHAR(255)  NOT NULL,
    version         BIGINT     NOT NULL,
    event_name      VARCHAR(255)  NOT NULL,
    event_data      TEXT           NOT NULL,
    created_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

INSERT INTO account_outbox_events (
    aggregate_id,
    aggregate_type,
    version,
    event_name,
    event_data,
    created_at
)
SELECT
    COALESCE(
        (event_data::jsonb ->> 'AggregateID'),
        (event_data::jsonb ->> 'AccountID'),
        'legacy'
    ) AS aggregate_id,
    COALESCE(
        (event_data::jsonb ->> 'AggregateType'),
        'account'
    ) AS aggregate_type,
    COALESCE(
        NULLIF((event_data::jsonb ->> 'Version'), '')::BIGINT,
        1
    ) AS version,
    SUBSTRING(event_name, 1, 255) AS event_name,
    event_data AS event_data,
    created_at
FROM account_outbox_events_old;

DROP TABLE account_outbox_events_old CASCADE;

CREATE INDEX idx_acc_outbox_aggregate_id ON account_outbox_events(aggregate_id);

CREATE INDEX idx_acc_outbox_aggregate_type ON account_outbox_events(aggregate_type);

CREATE INDEX idx_acc_outbox_event_name ON account_outbox_events(event_name);
