// Code generated by MockGen. DO NOT EDIT.
// Source: core/modules/payment/domain/repos/provider_payment_repo.go
//
// Generated by this command:
//
//	mockgen -package=repos -destination=core/modules/payment/domain/repos/provider_payment_repo_mock.go -source=core/modules/payment/domain/repos/provider_payment_repo.go
//

// Package repos is a generated GoMock package.
package repos

import (
	context "context"
	aggregate "go-socket/core/modules/payment/domain/aggregate"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProviderPaymentRepository is a mock of ProviderPaymentRepository interface.
type MockProviderPaymentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProviderPaymentRepositoryMockRecorder
	isgomock struct{}
}

// MockProviderPaymentRepositoryMockRecorder is the mock recorder for MockProviderPaymentRepository.
type MockProviderPaymentRepositoryMockRecorder struct {
	mock *MockProviderPaymentRepository
}

// NewMockProviderPaymentRepository creates a new mock instance.
func NewMockProviderPaymentRepository(ctrl *gomock.Controller) *MockProviderPaymentRepository {
	mock := &MockProviderPaymentRepository{ctrl: ctrl}
	mock.recorder = &MockProviderPaymentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProviderPaymentRepository) EXPECT() *MockProviderPaymentRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProviderPaymentRepository) Create(ctx context.Context, arg1 *aggregate.PaymentIntentAggregate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProviderPaymentRepositoryMockRecorder) Create(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProviderPaymentRepository)(nil).Create), ctx, arg1)
}

// GetByExternalRef mocks base method.
func (m *MockProviderPaymentRepository) GetByExternalRef(ctx context.Context, provider, externalRef string) (*aggregate.PaymentIntentAggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByExternalRef", ctx, provider, externalRef)
	ret0, _ := ret[0].(*aggregate.PaymentIntentAggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByExternalRef indicates an expected call of GetByExternalRef.
func (mr *MockProviderPaymentRepositoryMockRecorder) GetByExternalRef(ctx, provider, externalRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByExternalRef", reflect.TypeOf((*MockProviderPaymentRepository)(nil).GetByExternalRef), ctx, provider, externalRef)
}

// GetByTransactionID mocks base method.
func (m *MockProviderPaymentRepository) GetByTransactionID(ctx context.Context, transactionID string) (*aggregate.PaymentIntentAggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTransactionID", ctx, transactionID)
	ret0, _ := ret[0].(*aggregate.PaymentIntentAggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTransactionID indicates an expected call of GetByTransactionID.
func (mr *MockProviderPaymentRepositoryMockRecorder) GetByTransactionID(ctx, transactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTransactionID", reflect.TypeOf((*MockProviderPaymentRepository)(nil).GetByTransactionID), ctx, transactionID)
}

// Save mocks base method.
func (m *MockProviderPaymentRepository) Save(ctx context.Context, arg1 *aggregate.PaymentIntentAggregate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockProviderPaymentRepositoryMockRecorder) Save(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockProviderPaymentRepository)(nil).Save), ctx, arg1)
}
