// Code generated by MockGen. DO NOT EDIT.
// Source: core/modules/ledger/application/projection/projector.go
//
// Generated by this command:
//
//	mockgen -package=projection -destination=core/modules/ledger/application/projection/projector_mock.go -source=core/modules/ledger/application/projection/projector.go
//

// Package projection is a generated GoMock package.
package projection

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProjector is a mock of Projector interface.
type MockProjector struct {
	ctrl     *gomock.Controller
	recorder *MockProjectorMockRecorder
	isgomock struct{}
}

// MockProjectorMockRecorder is the mock recorder for MockProjector.
type MockProjectorMockRecorder struct {
	mock *MockProjector
}

// NewMockProjector creates a new mock instance.
func NewMockProjector(ctrl *gomock.Controller) *MockProjector {
	mock := &MockProjector{ctrl: ctrl}
	mock.recorder = &MockProjectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjector) EXPECT() *MockProjectorMockRecorder {
	return m.recorder
}

// ProjectTransaction mocks base method.
func (m *MockProjector) ProjectTransaction(ctx context.Context, transaction *LedgerTransactionProjected) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProjectTransaction", ctx, transaction)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProjectTransaction indicates an expected call of ProjectTransaction.
func (mr *MockProjectorMockRecorder) ProjectTransaction(ctx, transaction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProjectTransaction", reflect.TypeOf((*MockProjector)(nil).ProjectTransaction), ctx, transaction)
}
