// Code generated by MockGen. DO NOT EDIT.
// Source: session_cache.go
//
// Generated by this command:
//
//	mockgen -package=cache -destination=session_cache_mock.go -source=session_cache.go
//

// Package cache is a generated GoMock package.
package cache

import (
	context "context"
	entity "go-socket/core/modules/account/domain/entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSessionCache is a mock of SessionCache interface.
type MockSessionCache struct {
	ctrl     *gomock.Controller
	recorder *MockSessionCacheMockRecorder
	isgomock struct{}
}

// MockSessionCacheMockRecorder is the mock recorder for MockSessionCache.
type MockSessionCacheMockRecorder struct {
	mock *MockSessionCache
}

// NewMockSessionCache creates a new mock instance.
func NewMockSessionCache(ctrl *gomock.Controller) *MockSessionCache {
	mock := &MockSessionCache{ctrl: ctrl}
	mock.recorder = &MockSessionCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionCache) EXPECT() *MockSessionCacheMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockSessionCache) Delete(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSessionCacheMockRecorder) Delete(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSessionCache)(nil).Delete), ctx, sessionID)
}

// Get mocks base method.
func (m *MockSessionCache) Get(ctx context.Context, sessionID string) (*entity.Session, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, sessionID)
	ret0, _ := ret[0].(*entity.Session)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockSessionCacheMockRecorder) Get(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSessionCache)(nil).Get), ctx, sessionID)
}

// Set mocks base method.
func (m *MockSessionCache) Set(ctx context.Context, session *entity.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockSessionCacheMockRecorder) Set(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockSessionCache)(nil).Set), ctx, session)
}
