// Code generated by MockGen. DO NOT EDIT.
// Source: ledger_transaction_aggregate_repo.go
//
// Generated by this command:
//
//	mockgen -package=repos -destination=ledger_transaction_aggregate_repo_mock.go -source=ledger_transaction_aggregate_repo.go
//

// Package repos is a generated GoMock package.
package repos

import (
	context "context"
	aggregate "go-socket/core/modules/ledger/domain/aggregate"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLedgerTransactionAggregateRepository is a mock of LedgerTransactionAggregateRepository interface.
type MockLedgerTransactionAggregateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLedgerTransactionAggregateRepositoryMockRecorder
	isgomock struct{}
}

// MockLedgerTransactionAggregateRepositoryMockRecorder is the mock recorder for MockLedgerTransactionAggregateRepository.
type MockLedgerTransactionAggregateRepositoryMockRecorder struct {
	mock *MockLedgerTransactionAggregateRepository
}

// NewMockLedgerTransactionAggregateRepository creates a new mock instance.
func NewMockLedgerTransactionAggregateRepository(ctrl *gomock.Controller) *MockLedgerTransactionAggregateRepository {
	mock := &MockLedgerTransactionAggregateRepository{ctrl: ctrl}
	mock.recorder = &MockLedgerTransactionAggregateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLedgerTransactionAggregateRepository) EXPECT() *MockLedgerTransactionAggregateRepositoryMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockLedgerTransactionAggregateRepository) Save(ctx context.Context, arg1 *aggregate.LedgerTransactionAggregate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockLedgerTransactionAggregateRepositoryMockRecorder) Save(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockLedgerTransactionAggregateRepository)(nil).Save), ctx, arg1)
}
