// Code generated by MockGen. DO NOT EDIT.
// Source: core/modules/ledger/domain/repos/ledger_repo.go
//
// Generated by this command:
//
//	mockgen -package=repos -destination=core/modules/ledger/domain/repos/ledger_repo_mock.go -source=core/modules/ledger/domain/repos/ledger_repo.go
//

// Package repos is a generated GoMock package.
package repos

import (
	context "context"
	reflect "reflect"
	entity "wechat-clone/core/modules/ledger/domain/entity"

	gomock "go.uber.org/mock/gomock"
)

// MockLedgerRepository is a mock of LedgerRepository interface.
type MockLedgerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLedgerRepositoryMockRecorder
	isgomock struct{}
}

// MockLedgerRepositoryMockRecorder is the mock recorder for MockLedgerRepository.
type MockLedgerRepositoryMockRecorder struct {
	mock *MockLedgerRepository
}

// NewMockLedgerRepository creates a new mock instance.
func NewMockLedgerRepository(ctrl *gomock.Controller) *MockLedgerRepository {
	mock := &MockLedgerRepository{ctrl: ctrl}
	mock.recorder = &MockLedgerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLedgerRepository) EXPECT() *MockLedgerRepositoryMockRecorder {
	return m.recorder
}

// CountTransactions mocks base method.
func (m *MockLedgerRepository) CountTransactions(ctx context.Context, accountID, currency string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTransactions", ctx, accountID, currency)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTransactions indicates an expected call of CountTransactions.
func (mr *MockLedgerRepositoryMockRecorder) CountTransactions(ctx, accountID, currency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTransactions", reflect.TypeOf((*MockLedgerRepository)(nil).CountTransactions), ctx, accountID, currency)
}

// GetBalance mocks base method.
func (m *MockLedgerRepository) GetBalance(ctx context.Context, accountID, currency string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, accountID, currency)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockLedgerRepositoryMockRecorder) GetBalance(ctx, accountID, currency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockLedgerRepository)(nil).GetBalance), ctx, accountID, currency)
}

// GetTransaction mocks base method.
func (m *MockLedgerRepository) GetTransaction(ctx context.Context, transactionID string) (*entity.LedgerTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransaction", ctx, transactionID)
	ret0, _ := ret[0].(*entity.LedgerTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransaction indicates an expected call of GetTransaction.
func (mr *MockLedgerRepositoryMockRecorder) GetTransaction(ctx, transactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransaction", reflect.TypeOf((*MockLedgerRepository)(nil).GetTransaction), ctx, transactionID)
}

// ListTransactions mocks base method.
func (m *MockLedgerRepository) ListTransactions(ctx context.Context, filter ListTransactionsFilter) ([]*entity.LedgerTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransactions", ctx, filter)
	ret0, _ := ret[0].([]*entity.LedgerTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTransactions indicates an expected call of ListTransactions.
func (mr *MockLedgerRepositoryMockRecorder) ListTransactions(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransactions", reflect.TypeOf((*MockLedgerRepository)(nil).ListTransactions), ctx, filter)
}
