// Code generated by MockGen. DO NOT EDIT.
// Source: payment_command_service.go
//
// Generated by this command:
//
//	mockgen -package=service -destination=payment_command_service_mock.go -source=payment_command_service.go
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"
	in "wechat-clone/core/modules/payment/application/dto/in"
	out "wechat-clone/core/modules/payment/application/dto/out"

	gomock "go.uber.org/mock/gomock"
)

// MockPaymentCommandService is a mock of PaymentCommandService interface.
type MockPaymentCommandService struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentCommandServiceMockRecorder
	isgomock struct{}
}

// MockPaymentCommandServiceMockRecorder is the mock recorder for MockPaymentCommandService.
type MockPaymentCommandServiceMockRecorder struct {
	mock *MockPaymentCommandService
}

// NewMockPaymentCommandService creates a new mock instance.
func NewMockPaymentCommandService(ctrl *gomock.Controller) *MockPaymentCommandService {
	mock := &MockPaymentCommandService{ctrl: ctrl}
	mock.recorder = &MockPaymentCommandServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentCommandService) EXPECT() *MockPaymentCommandServiceMockRecorder {
	return m.recorder
}

// CreatePayment mocks base method.
func (m *MockPaymentCommandService) CreatePayment(ctx context.Context, req *in.CreatePaymentRequest) (*out.CreatePaymentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePayment", ctx, req)
	ret0, _ := ret[0].(*out.CreatePaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePayment indicates an expected call of CreatePayment.
func (mr *MockPaymentCommandServiceMockRecorder) CreatePayment(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePayment", reflect.TypeOf((*MockPaymentCommandService)(nil).CreatePayment), ctx, req)
}

// CreateWithdrawal mocks base method.
func (m *MockPaymentCommandService) CreateWithdrawal(ctx context.Context, req *in.CreateWithdrawalRequest) (*out.CreateWithdrawalResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithdrawal", ctx, req)
	ret0, _ := ret[0].(*out.CreateWithdrawalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWithdrawal indicates an expected call of CreateWithdrawal.
func (mr *MockPaymentCommandServiceMockRecorder) CreateWithdrawal(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithdrawal", reflect.TypeOf((*MockPaymentCommandService)(nil).CreateWithdrawal), ctx, req)
}

// ProcessPendingWithdrawals mocks base method.
func (m *MockPaymentCommandService) ProcessPendingWithdrawals(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessPendingWithdrawals", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessPendingWithdrawals indicates an expected call of ProcessPendingWithdrawals.
func (mr *MockPaymentCommandServiceMockRecorder) ProcessPendingWithdrawals(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessPendingWithdrawals", reflect.TypeOf((*MockPaymentCommandService)(nil).ProcessPendingWithdrawals), ctx)
}

// ProcessWebhook mocks base method.
func (m *MockPaymentCommandService) ProcessWebhook(ctx context.Context, req *in.ProcessWebhookRequest) (*out.ProcessWebhookResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessWebhook", ctx, req)
	ret0, _ := ret[0].(*out.ProcessWebhookResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessWebhook indicates an expected call of ProcessWebhook.
func (mr *MockPaymentCommandServiceMockRecorder) ProcessWebhook(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessWebhook", reflect.TypeOf((*MockPaymentCommandService)(nil).ProcessWebhook), ctx, req)
}
