// Code generated by MockGen. DO NOT EDIT.
// Source: chat_query_service.go
//
// Generated by this command:
//
//	mockgen -package=service -destination=chat_query_service_mock.go -source=chat_query_service.go
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	types "go-socket/core/modules/room/application/types"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockChatQueryService is a mock of ChatQueryService interface.
type MockChatQueryService struct {
	ctrl     *gomock.Controller
	recorder *MockChatQueryServiceMockRecorder
	isgomock struct{}
}

// MockChatQueryServiceMockRecorder is the mock recorder for MockChatQueryService.
type MockChatQueryServiceMockRecorder struct {
	mock *MockChatQueryService
}

// NewMockChatQueryService creates a new mock instance.
func NewMockChatQueryService(ctrl *gomock.Controller) *MockChatQueryService {
	mock := &MockChatQueryService{ctrl: ctrl}
	mock.recorder = &MockChatQueryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatQueryService) EXPECT() *MockChatQueryServiceMockRecorder {
	return m.recorder
}

// GetConversation mocks base method.
func (m *MockChatQueryService) GetConversation(ctx context.Context, accountID string, query types.GetConversationQuery) (*types.ConversationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConversation", ctx, accountID, query)
	ret0, _ := ret[0].(*types.ConversationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConversation indicates an expected call of GetConversation.
func (mr *MockChatQueryServiceMockRecorder) GetConversation(ctx, accountID, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConversation", reflect.TypeOf((*MockChatQueryService)(nil).GetConversation), ctx, accountID, query)
}

// GetPresence mocks base method.
func (m *MockChatQueryService) GetPresence(ctx context.Context, query types.GetPresenceQuery) (*types.PresenceResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPresence", ctx, query)
	ret0, _ := ret[0].(*types.PresenceResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPresence indicates an expected call of GetPresence.
func (mr *MockChatQueryServiceMockRecorder) GetPresence(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPresence", reflect.TypeOf((*MockChatQueryService)(nil).GetPresence), ctx, query)
}

// ListConversations mocks base method.
func (m *MockChatQueryService) ListConversations(ctx context.Context, accountID string, query types.ListConversationsQuery) ([]types.ConversationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConversations", ctx, accountID, query)
	ret0, _ := ret[0].([]types.ConversationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListConversations indicates an expected call of ListConversations.
func (mr *MockChatQueryServiceMockRecorder) ListConversations(ctx, accountID, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConversations", reflect.TypeOf((*MockChatQueryService)(nil).ListConversations), ctx, accountID, query)
}

// ListMessages mocks base method.
func (m *MockChatQueryService) ListMessages(ctx context.Context, accountID string, query types.ListMessagesQuery) ([]types.MessageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMessages", ctx, accountID, query)
	ret0, _ := ret[0].([]types.MessageResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMessages indicates an expected call of ListMessages.
func (mr *MockChatQueryServiceMockRecorder) ListMessages(ctx, accountID, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMessages", reflect.TypeOf((*MockChatQueryService)(nil).ListMessages), ctx, accountID, query)
}

// SearchMentionCandidates mocks base method.
func (m *MockChatQueryService) SearchMentionCandidates(ctx context.Context, accountID string, query types.SearchMentionCandidatesQuery) ([]types.MentionCandidateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchMentionCandidates", ctx, accountID, query)
	ret0, _ := ret[0].([]types.MentionCandidateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchMentionCandidates indicates an expected call of SearchMentionCandidates.
func (mr *MockChatQueryServiceMockRecorder) SearchMentionCandidates(ctx, accountID, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchMentionCandidates", reflect.TypeOf((*MockChatQueryService)(nil).SearchMentionCandidates), ctx, accountID, query)
}
