// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -package=service -destination=service_mock.go -source=service.go
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"
	types "wechat-clone/core/modules/room/application/types"
	types0 "wechat-clone/core/modules/room/types"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// EmitMessage mocks base method.
func (m *MockService) EmitMessage(ctx context.Context, message types0.MessagePayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmitMessage", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// EmitMessage indicates an expected call of EmitMessage.
func (mr *MockServiceMockRecorder) EmitMessage(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmitMessage", reflect.TypeOf((*MockService)(nil).EmitMessage), ctx, message)
}

// GetConversation mocks base method.
func (m *MockService) GetConversation(ctx context.Context, accountID string, query types.GetConversationQuery) (*types.ConversationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConversation", ctx, accountID, query)
	ret0, _ := ret[0].(*types.ConversationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConversation indicates an expected call of GetConversation.
func (mr *MockServiceMockRecorder) GetConversation(ctx, accountID, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConversation", reflect.TypeOf((*MockService)(nil).GetConversation), ctx, accountID, query)
}

// GetPresence mocks base method.
func (m *MockService) GetPresence(ctx context.Context, query types.GetPresenceQuery) (*types.PresenceResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPresence", ctx, query)
	ret0, _ := ret[0].(*types.PresenceResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPresence indicates an expected call of GetPresence.
func (mr *MockServiceMockRecorder) GetPresence(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPresence", reflect.TypeOf((*MockService)(nil).GetPresence), ctx, query)
}

// GetRoom mocks base method.
func (m *MockService) GetRoom(ctx context.Context, query types.GetRoomQuery) (*types.RoomResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoom", ctx, query)
	ret0, _ := ret[0].(*types.RoomResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoom indicates an expected call of GetRoom.
func (mr *MockServiceMockRecorder) GetRoom(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoom", reflect.TypeOf((*MockService)(nil).GetRoom), ctx, query)
}

// ListConversations mocks base method.
func (m *MockService) ListConversations(ctx context.Context, accountID string, query types.ListConversationsQuery) ([]types.ConversationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConversations", ctx, accountID, query)
	ret0, _ := ret[0].([]types.ConversationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListConversations indicates an expected call of ListConversations.
func (mr *MockServiceMockRecorder) ListConversations(ctx, accountID, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConversations", reflect.TypeOf((*MockService)(nil).ListConversations), ctx, accountID, query)
}

// ListMessages mocks base method.
func (m *MockService) ListMessages(ctx context.Context, accountID string, query types.ListMessagesQuery) ([]types.MessageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMessages", ctx, accountID, query)
	ret0, _ := ret[0].([]types.MessageResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMessages indicates an expected call of ListMessages.
func (mr *MockServiceMockRecorder) ListMessages(ctx, accountID, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMessages", reflect.TypeOf((*MockService)(nil).ListMessages), ctx, accountID, query)
}

// ListRooms mocks base method.
func (m *MockService) ListRooms(ctx context.Context, query types.ListRoomsQuery) (*types.ListRoomsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRooms", ctx, query)
	ret0, _ := ret[0].(*types.ListRoomsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRooms indicates an expected call of ListRooms.
func (mr *MockServiceMockRecorder) ListRooms(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRooms", reflect.TypeOf((*MockService)(nil).ListRooms), ctx, query)
}

// SearchMentionCandidates mocks base method.
func (m *MockService) SearchMentionCandidates(ctx context.Context, accountID string, query types.SearchMentionCandidatesQuery) ([]types.MentionCandidateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchMentionCandidates", ctx, accountID, query)
	ret0, _ := ret[0].([]types.MentionCandidateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchMentionCandidates indicates an expected call of SearchMentionCandidates.
func (mr *MockServiceMockRecorder) SearchMentionCandidates(ctx, accountID, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchMentionCandidates", reflect.TypeOf((*MockService)(nil).SearchMentionCandidates), ctx, accountID, query)
}

// MockQueryService is a mock of QueryService interface.
type MockQueryService struct {
	ctrl     *gomock.Controller
	recorder *MockQueryServiceMockRecorder
	isgomock struct{}
}

// MockQueryServiceMockRecorder is the mock recorder for MockQueryService.
type MockQueryServiceMockRecorder struct {
	mock *MockQueryService
}

// NewMockQueryService creates a new mock instance.
func NewMockQueryService(ctrl *gomock.Controller) *MockQueryService {
	mock := &MockQueryService{ctrl: ctrl}
	mock.recorder = &MockQueryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryService) EXPECT() *MockQueryServiceMockRecorder {
	return m.recorder
}

// GetConversation mocks base method.
func (m *MockQueryService) GetConversation(ctx context.Context, accountID string, query types.GetConversationQuery) (*types.ConversationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConversation", ctx, accountID, query)
	ret0, _ := ret[0].(*types.ConversationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConversation indicates an expected call of GetConversation.
func (mr *MockQueryServiceMockRecorder) GetConversation(ctx, accountID, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConversation", reflect.TypeOf((*MockQueryService)(nil).GetConversation), ctx, accountID, query)
}

// GetPresence mocks base method.
func (m *MockQueryService) GetPresence(ctx context.Context, query types.GetPresenceQuery) (*types.PresenceResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPresence", ctx, query)
	ret0, _ := ret[0].(*types.PresenceResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPresence indicates an expected call of GetPresence.
func (mr *MockQueryServiceMockRecorder) GetPresence(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPresence", reflect.TypeOf((*MockQueryService)(nil).GetPresence), ctx, query)
}

// GetRoom mocks base method.
func (m *MockQueryService) GetRoom(ctx context.Context, query types.GetRoomQuery) (*types.RoomResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoom", ctx, query)
	ret0, _ := ret[0].(*types.RoomResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoom indicates an expected call of GetRoom.
func (mr *MockQueryServiceMockRecorder) GetRoom(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoom", reflect.TypeOf((*MockQueryService)(nil).GetRoom), ctx, query)
}

// ListConversations mocks base method.
func (m *MockQueryService) ListConversations(ctx context.Context, accountID string, query types.ListConversationsQuery) ([]types.ConversationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConversations", ctx, accountID, query)
	ret0, _ := ret[0].([]types.ConversationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListConversations indicates an expected call of ListConversations.
func (mr *MockQueryServiceMockRecorder) ListConversations(ctx, accountID, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConversations", reflect.TypeOf((*MockQueryService)(nil).ListConversations), ctx, accountID, query)
}

// ListMessages mocks base method.
func (m *MockQueryService) ListMessages(ctx context.Context, accountID string, query types.ListMessagesQuery) ([]types.MessageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMessages", ctx, accountID, query)
	ret0, _ := ret[0].([]types.MessageResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMessages indicates an expected call of ListMessages.
func (mr *MockQueryServiceMockRecorder) ListMessages(ctx, accountID, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMessages", reflect.TypeOf((*MockQueryService)(nil).ListMessages), ctx, accountID, query)
}

// ListRooms mocks base method.
func (m *MockQueryService) ListRooms(ctx context.Context, query types.ListRoomsQuery) (*types.ListRoomsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRooms", ctx, query)
	ret0, _ := ret[0].(*types.ListRoomsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRooms indicates an expected call of ListRooms.
func (mr *MockQueryServiceMockRecorder) ListRooms(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRooms", reflect.TypeOf((*MockQueryService)(nil).ListRooms), ctx, query)
}

// SearchMentionCandidates mocks base method.
func (m *MockQueryService) SearchMentionCandidates(ctx context.Context, accountID string, query types.SearchMentionCandidatesQuery) ([]types.MentionCandidateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchMentionCandidates", ctx, accountID, query)
	ret0, _ := ret[0].([]types.MentionCandidateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchMentionCandidates indicates an expected call of SearchMentionCandidates.
func (mr *MockQueryServiceMockRecorder) SearchMentionCandidates(ctx, accountID, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchMentionCandidates", reflect.TypeOf((*MockQueryService)(nil).SearchMentionCandidates), ctx, accountID, query)
}
