// Code generated by MockGen. DO NOT EDIT.
// Source: session_aggregate_repo.go
//
// Generated by this command:
//
//	mockgen -package=repos -destination=session_aggregate_repo_mock.go -source=session_aggregate_repo.go
//

// Package repos is a generated GoMock package.
package repos

import (
	context "context"
	reflect "reflect"
	aggregate "wechat-clone/core/modules/account/domain/aggregate"

	gomock "go.uber.org/mock/gomock"
)

// MockSessionAggregateRepository is a mock of SessionAggregateRepository interface.
type MockSessionAggregateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionAggregateRepositoryMockRecorder
	isgomock struct{}
}

// MockSessionAggregateRepositoryMockRecorder is the mock recorder for MockSessionAggregateRepository.
type MockSessionAggregateRepositoryMockRecorder struct {
	mock *MockSessionAggregateRepository
}

// NewMockSessionAggregateRepository creates a new mock instance.
func NewMockSessionAggregateRepository(ctrl *gomock.Controller) *MockSessionAggregateRepository {
	mock := &MockSessionAggregateRepository{ctrl: ctrl}
	mock.recorder = &MockSessionAggregateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionAggregateRepository) EXPECT() *MockSessionAggregateRepositoryMockRecorder {
	return m.recorder
}

// ListByAccountID mocks base method.
func (m *MockSessionAggregateRepository) ListByAccountID(ctx context.Context, accountID string) ([]*aggregate.SessionAggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAccountID", ctx, accountID)
	ret0, _ := ret[0].([]*aggregate.SessionAggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAccountID indicates an expected call of ListByAccountID.
func (mr *MockSessionAggregateRepositoryMockRecorder) ListByAccountID(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAccountID", reflect.TypeOf((*MockSessionAggregateRepository)(nil).ListByAccountID), ctx, accountID)
}

// Load mocks base method.
func (m *MockSessionAggregateRepository) Load(ctx context.Context, sessionID string) (*aggregate.SessionAggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, sessionID)
	ret0, _ := ret[0].(*aggregate.SessionAggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockSessionAggregateRepositoryMockRecorder) Load(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockSessionAggregateRepository)(nil).Load), ctx, sessionID)
}

// Save mocks base method.
func (m *MockSessionAggregateRepository) Save(ctx context.Context, session *aggregate.SessionAggregate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockSessionAggregateRepositoryMockRecorder) Save(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSessionAggregateRepository)(nil).Save), ctx, session)
}
